version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "local"
      MYSQL_DATABASE: "local"
      MYSQL_USER: "local"
      MYSQL_PASSWORD: "local"
    ports:
      - "3306:3306"
    networks:
      - bank-network

networks:
  bank-network:
